PRAGMA foreign_keys = ON;

-- Reports are historical/current views, not a mechanism for creating future debt.
-- Remove any future dues that may have been generated by opening a future report.
-- Allocation rows are removed automatically through ON DELETE CASCADE, restoring
-- those receipt amounts to available credit until a real due exists.
DELETE FROM monthly_dues_v5
WHERE month > strftime('%Y-%m','now');
